package com.bachir.owner.blayes;

/**
 * Created by bachir on 5/20/2016.
 */
public final class Constants {

    public static final CharSequence wilaya1[] = new CharSequence[] {"Wilaya d'Adrar", "Wilaya de Chlef", "Laghouat Province", "Wilaya d'Oum El Bouaghi", "Wilaya de Batna", "Wilaya de Béjaïa", "Wilaya de Biskra", "Béchar Province", "Wilaya de Blida", "Wilaya de Bouira", "Tamanrasset Province", "Wilaya de Tébessa", "Wilaya de Tlemcen", "Wilaya de Tiaret", "Wilaya de Tizi Ouzou", "Wilaya d'Alger", "Wilaya de Djelfa", "Wilaya de Jijel", "Wilaya de Sétif", "Wilaya de Saïda", "Wilaya de Skikda", "Wilaya de Sidi Bel Abbès", "Wilaya d'Annaba", "Wilaya de Guelma", "Constantine Province", "Wilaya de Médéa", "Wilaya de Mostaganem", "Wilaya de M'Sila", "Wilaya de Mascara", "Wilaya d'Ouargla", "Oran Province", "Wilaya d'El Bayadh", "Illizi Province", "Bordj Bou Arréridj Province", "Wilaya de Boumerdès", "Wilaya d'El Tarf", "Tindouf Province", "Wilaya de Tissemsilt", "Wilaya d'El Oued", "Wilaya de Khenchela", "Wilaya de Souk Ahras", "Wilaya de Tipaza", "Wilaya de Mila", "Wilaya de Aïn Defla", "Wilaya de Naâma", "Wilaya d'Aïn Témouchent", "Wilaya de Ghardaïa", "Wilaya de Relizane"};
    public static final CharSequence wilaya[] = new CharSequence[] {"01. Adrar", "02. Chlef", "03. Laghouat", "04. Oum el-Bouaghi", "05. Batna", "06. Béjaïa", "07. Biskra", "08. Béchar", "09. Blida", "10. Bouïra", "11. Tamanghasset", "12. Tébessa", "13. Tlemcen", "14. Tiaret", "15. Tizi Ouzou", "16. Alger", "17. Djelfa", "18. Jijel", "19. Sétif", "20. Saïda", "21. Skikda", "22. Sidi Bel Abbès", "23. Annaba", "24. Guelma", "25. Constantine", "26. Médéa", "27. Mostaganem", "28. M'Sila", "29. Mascara", "30. Ouargla", "31. Oran", "32. El Bayadh", "33. Illizi", "34. Bordj Bou Arréridj", "35. Boumerdès", "36. El Taref", "37. Tindouf", "38. Tissemsilt", "39. El Oued", "40. Khenchela", "41. Souk Ahras", "42. Tipasa", "43. Mila", "44. Aïn Defla", "45. Naâma", "46. Aïn Témouchent", "47. Ghardaïa", "48. Relizane"};
    public static final CharSequence wilaya0[] = new CharSequence[] {"Adrar", "Chlef", "Laghouat", "Oum el-Bouaghi", "Batna", "Béjaïa", "Biskra", "Béchar", "Blida", "Bouïra", "Tamanghasset", "Tébessa", "Tlemcen", "Tiaret", "Tizi Ouzou", "Alger", "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda", "Sidi Bel Abbès", "Annaba", "Guelma", "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara", "Ouargla", "Oran", "El Bayadh", "Illizi", "Bordj Bou Arréridj", "Boumerdès", "El Taref", "Tindouf", "Tissemsilt", "El Oued", "Khenchela", "Souk Ahras", "Tipasa", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent", "Ghardaïa", "Relizane"};
    public static final CharSequence commune[][] = new CharSequence[][] {
            {"(Peu importe)", "Adrar", "Tamest", "Gharouine", "Reggane", "Inzegmir", "Tit", "Ksar Kaddour", "Tsabit", "Timimoun", "Ouled Said", "Zaouiet Kounta", "Aoulef", "Timokten", "Tamentit", "Fenoughil", "Tinerkouk", "Deldoul", "Sali", "Akabili", "Metarfa", "Ouled Ahmed Timi", "Bouda", "Aougrout", "Talmine", "Bordj Badji Mokhtar", "Sebaa", "Ouled Aissa", "Timiaouine"},
            {"(Peu importe)", "Chlef", "Tenes", "Benairia", "El Karimia", "Tadjena", "Taougrite", "Beni Haoua", "Sobha", "Harchoun", "Ouled Fares", "Sidi Akkacha", "Boukadir", "Beni Rached", "Talassa", "Herenfa", "Oued Ghoussine", "Dahra", "Ouled Abbes", "Sendjas", "Zeboudja", "Oued Sly", "Abou El Hassen", "El Marsa", "Chettia", "Sidi Abderrahmane", "Moussadek", "El Hadjadj", "Labiodh Medjadja", "Oued Fodda", "Ouled Ben Abdelkader", "Bouzeghaia", "Ain Merane", "Oum Drou", "Breira", "Beni Bouattab"},
            {"(Peu importe)", "Laghouat", "Ksar El Hirane", "Mekhareg", "Sidi Makhlouf", "Hassi Dhelaa", "Hassi Rmel", "Ain Madhi", "Tadjemout", "Kheneg", "Gueltat Sidi Saad", "Ain Sidi Ali", "Beidha", "Brida", "El Ghicha", "Hadj Mechri", "Sebgag", "Taouila", "Tadjrouna", "Aflou", "El Assafia", "Oued Morra", "Oued Mzi", "El Haouaita", "Sidi Bouzid"},
            {"(Peu importe)", "Oum El Bouaghi", "Ain Beida", "Ain Mlila", "Behir Chergui", "El Amiria", "Sigus", "El Belala", "Ain Babouche", "Berriche", "Ouled Hamla", "Dhalaa", "Ain Kercha", "Hanchir Toumghani", "El Djezia", "Ain Diss", "Fkirina", "Souk Naamane", "El Zorg", "El Fedjoudj Boughrara Saoudi", "Ouled Zouai", "Bir Chouhada", "Ksar Sbahi", "Oued Nini", "Meskiana", "Ain Fakroun", "Rehia", "Ain Zitoun", "Ouled Gacem", "El Harmilia"},
            {"(Peu importe)", "Batna", "Ghassira", "Maafa", "Merouana", "Seriana", "Menaa", "El Madher", "Tazoult", "Ngaous", "Guigba", "Inoughissene", "Ouyoun El Assafir", "Djerma", "Bitam", "Metkaouak", "Arris", "Kimmel", "Tilatou", "Ain Djasser", "Ouled Sellam", "Tigharghar", "Ain Yagout", "Fesdis", "Sefiane", "Rahbat", "Tighanimine", "Lemcen", "Ksar Belezma", "Seggana", "Ichemoul", "Foum Toub", "Beni Foudhala El Hakania", "Oued El Ma", "Talkhemt", "Bouzina", "Chemora", "Oued Chaaba", "Taxlent", "Gosbat", "Ouled Aouf", "Boumague", "Barika", "Djezzar", "Tkout", "Ain Touta", "Hidoussa", "Theniet El Abed", "Oued Taga", "Ouled Fadel", "Timgad", "Ras El Aioun", "Chir", "Ouled Si Slimane", "Zana El Beida", "Mdoukal", "Ouled Ammar", "El Hassi", "Lazrou", "Boumia", "Boulehilet", "Larbaa"},
            {"(Peu importe)", "Bejaia", "Amizour", "Ferraoun", "Taourirt Ighil", "Chelata", "Tamokra", "Timzrit", "Souk El Thenine", "Sidi Said", "Tinebdar", "Tichi", "Semaoune", "Kendira", "Tifra", "Ighram", "Amalou", "Ighil Ali", "Ifelain Ilmathen", "Toudja", "Darguina", "Sidi Ayad", "Aokas", "Beni Djellil", "Adekar", "Akbou", "Seddouk", "Tazmalt", "Ait R_zine", "Chemini", "Souk Oufella", "Taskriout", "Tibane", "Tala Hamza", "Barbacha", "Beni Ksila", "Ouzellaguen", "Bouhamza", "Beni Melikech", "Sidi Aich", "El Kseur", "Melbou", "Akfadou", "Leflaye", "Kherrata", "Draa El Kaid", "Tamridjet", "Ait Smail", "Boukhelifa", "Tizi Nberber", "Beni Maouche", "Oued Ghir", "Boudjellil"},
            {"(Peu importe)", "Biskra", "Oumache", "Branis", "Chetma", "Ouled Djellal", "Ras El Miaad", "Besbes", "Sidi Khaled", "Doucen", "Ech Chaiba", "Sidi Okba", "M_chouneche", "El Haouch", "Ain Naga", "Zeribet El Oued", "El Feidh", "El Kantara", "Ain Zaatout", "El Outaya", "Djemorah", "Tolga", "Lioua", "Lichana", "Oughlal", "Mlili", "Foughala", "Bordj Ben Azzouz", "M_ziraa", "Bouchagroun", "Mekhadma", "El Ghrous", "El Hadjeb", "Khangat Sidi Nadji"},
            {"(Peu importe)", "Bechar", "Erg Ferradj", "Ouled Khoudir", "Meridja", "Timmoudi", "Lahmar", "Beni Abbes", "Beni Ikhlef", "Mechraa Houari Boumediene", "Kenadsa", "Igli", "Tabelbala", "Taghit", "El Ouata", "Boukais", "Mougheul", "Abadla", "Kerzaz", "Ksabi", "Tamert", "Beni Ounif"},
            {"(Peu importe)", "Blida", "Chebli", "Bouinan", "Oued El Alleug", "Ouled Yaich", "Chrea", "El Affroun", "Chiffa", "Hammam Melouane", "Ben Khelil", "Soumaa", "Mouzaia", "Souhane", "Meftah", "Ouled Slama", "Boufarik", "Larbaa", "Oued Djer", "Beni Tamou", "Bouarfa", "Beni Mered", "Bougara", "Guerrouaou", "Djebabra", "Ain Romana"},
            {"(Peu importe)", "Bouira", "El Asnam", "Guerrouma", "Souk El Khemis", "Kadiria", "Hanif", "Dirah", "Ait Laaziz", "Taghzout", "Raouraoua", "Mezdour", "Haizer", "Lakhdaria", "Maala", "El Hachimia", "Aomar", "Chorfa", "Bordj Oukhriss", "El Adjiba", "El Hakimia", "El Khabouzia", "Ahl El Ksar", "Bouderbala", "Zbarbar", "Ain El Hadjar", "Djebahia", "Aghbalou", "Taguedit", "Ain Turk", "Saharidj", "Dechmia", "Ridane", "Bechloul", "Boukram", "Ain Bessam", "Bir Ghbalou", "Mchedallah", "Sour El Ghozlane", "Maamora", "Ouled Rached", "Ain Laloui", "Hadjera Zerga", "Ath Mansour", "El Mokrani", "Oued El Berdi"},
            {"(Peu importe)", "Tamanrasset", "Abalessa", "In Ghar", "In Guezzam", "Idles", "Tazrouk", "Tin Zaouatine", "In Salah", "In Amguel", "Fouggarat Ez Zouaia"},
            {"(Peu importe)", "Tebessa", "Bir El Ater", "Cheria", "Stah Guentis", "El Aouinet", "El Houidjbet", "Safsaf El Ouesra", "Hammamet", "Negrine", "Bir Mokadem", "El Kouif", "Morsot", "El Ogla", "Bir Dheheb", "El Ogla El Malha", "Gourigueur", "Bekkaria", "Boukhadra", "El Ouenza", "El Ma Labiod", "Oum Ali", "Thlidjene", "Ain Zerga", "El Meridj", "Boulhaf Dyr", "Bedjene", "El Mazeraa", "Ferkane"},
            {"(Peu importe)", "Tlemcen", "Beni Mester", "Ain Tallout", "Remchi", "El Fehoul", "Sabra", "Ghazaouet", "Souani", "Djebala", "El Gor", "Oued Chouly", "Ain Fezza", "Ouled Mimoun", "Amieur", "Ain Youcef", "Zenata", "Beni Snous", "Bab El Assa", "Dar Yaghmourassene", "Fellaoucene", "Azails", "Sebaa Chioukh", "Terni Beni Hediel", "Bensekrane", "Ain Nehala", "Henaya", "Maghnia", "Hammam Boughrara", "Souahlia", "Msirda Fouaga", "Ain Fetah", "El Aricha", "Souk Thlata", "Sidi Abdelli", "Sebdou", "Beni Ouarsous", "Sidi Medjahed", "Beni Boussaid", "Mersa Ben Mhidi", "Nedroma", "Sidi Djillali", "Beni Bahdel", "El Bouihi", "Honaine", "Tienet", "Ouled Riah", "Bouhlou", "Beni Khellad", "Beni Khellad", "Ain Ghoraba", "Chetouane", "Mansourah", "Beni Semiel", "Ain Kebira"},
            {"(Peu importe)", "Tiaret", "Medroussa", "Ain Bouchekif", "Sidi Ali Mellal", "Ain Zarit", "Ain Deheb", "Sidi Bakhti", "Medrissa", "Zmalet Emir Abdelkader", "Madna", "Sebt", "Mellakou", "Dahmouni", "Rahouia", "Mahdia", "Sougueur", "Sidi  Abdelghani", "Ain El Hadid", "Djebilet Rosfa", "Naima", "Meghila", "Guertoufa", "Sidi Hosni", "Djillali Ben Amar", "Sebaine", "Tousnina", "Frenda", "Ain Kermes", "Ksar Chellala", "Rechaiga", "Nadorah", "Tagdemt", "Oued Lilli", "Machraa Sfa", "Hamadia", "Chehaima", "Takhmaret", "Sidi Abderrahmane", "Serghine", "Bougara", "Faidja", "Tidda"},
            {"(Peu importe)", "Tizi Ouzou", "Ain El Hammam", "Akbil", "Freha", "Souamaa", "Mechtrass", "Irdjen", "Timizart", "Makouda", "Draa El Mizan", "Tizi Ghenif", "Bounouh", "Ait Chaffaa", "Frikat", "Beni Aissi", "Beni Zmenzer", "Iferhounene", "Azazga", "Iloula Oumalou", "Yakouren", "Larba Nait Irathen", "Tizi Rached", "Zekri", "Ouaguenoun", "Ain Zaouia", "Mkira", "Ait Yahia", "Ait Mahmoud", "Maatka", "Ait Boumahdi", "Abi Youcef", "Beni Douala", "Illilten", "Bouzguen", "Ait Aggouacha", "Ouadhia", "Azeffoun", "Tigzirt", "Ait Aissa Mimoun", "Boghni", "Ifigha", "Ait Oumalou", "Tirmitine", "Akerrou", "Yatafen", "Beni Ziki", "Draa Ben Khedda", "Ouacif", "Idjeur", "Mekla", "Tizi Nthleta", "Beni Yenni", "Aghrib", "Iflissen", "Iflissen", "Boudjima", "Ait Yahia Moussa", "Souk El Tenine", "Ait Khelili", "Sidi Naamane", "Iboudraren", "Aghni Goughran", "Mizrana", "Imsouhal", "Tadmait", "Ait Bouadou", "Assi Youcef", "Ait Toudert"},
            {"(Peu importe)", "Alger", "Sidi Mhamed", "El Madania", "Hamma Anassers", "Bab El Oued", "Bologhine Ibn Ziri", "Casbah", "Oued Koriche", "Bir Mourad Rais", "El Biar", "Bouzareah", "Bir Khadem", "El Harrach", "Baraki", "Oued Smar", "Bourouba", "Hussein Dey", "Kouba", "Bach Djerrah", "Dar El Beida", "Beb Ezzouar", "Ben Aknoun", "Dely Brahim", "Bains Romains", "Rais Hamidou", "Djisr Ksentina", "El Mouradia", "Hydra", "Mohammadia", "Bordj El Kiffan", "El Magharia", "Beni Messous", "Les Eucalyptus", "Birtouta", "Tassala El Merdja", "Ouled Chebel", "Sidi Moussa", "Ain Taya", "Bordj El Bahri", "El Marsa", "Haraoua", "Rouiba", "Reghaia", "Ain Benian", "Staoueli", "Zeralda", "Mahelma", "Rahmania", "Souidania", "Cheraga", "Ouled Fayet", "El Achour", "Draria", "Douera", "Baba Hassen", "Khraissia", "Saoula"},
            {"(Peu importe)", "Djelfa", "Mouadjebar", "El Gueddid", "Hassi Bahbah", "Ain Maabed", "Sed Rahal", "Feidh El Botma", "Birine", "Bouira Lahdab", "Zakkar", "El Khemis", "Sidi Baizid", "Mliliha", "El Idrissia", "Douis", "Hassi El Euch", "Messaad", "Guettara", "Sidi Laadjel", "Had Sahary", "Guernini", "Selmana", "Ain Chouhada", "Oum Laadham", "Dar Chioukh", "Charef", "Beni Yagoub", "Zaafrane", "Deldoul", "Ain El Ibel", "Ain Ouessara", "Benhar", "Hassi Fdoul", "Amoura", "Ain Fekka", "Tadmit"},
            {"(Peu importe)", "Jijel", "Erraguene", "El Aouana", "Ziama Mansouria", "Taher", "Emir Abdelkader", "Chekfa", "Chahna", "El Milia", "Sidi Maarouf", "Settara", "El Ancer", "Sidi Abdelaziz", "Kaous", "Chebbala Milat", "Bouraoui Belhadef", "Djmila", "Selma Ben Ziada", "Boussif Ouled Akseur", "El Kennar Nouchfi", "Ouled Yahia Khadrouche", "Boudria Beni Yadjis", "Kimir Oued Adjoul", "Texenna", "Djemaa Beni Habibi", "Bordj Taher", "Ouled Rabah", "Oudjana"},
            {"(Peu importe)", "Setif", "Ain El Kebira", "Beni Aziz", "Ouled Sidi Ahmed", "Boutaleb", "Ain Roua", "Draa Kebila", "Bir El Arch", "Beni Chebana", "Ouled Tebben", "Hamma", "Maaouia", "Ain Lagradj", "Ain Abessa", "Dehamcha", "Babor", "Guidjel", "Ain Lahdjar", "Bousselam", "El Eulma", "Djemila", "Beni Ouartilane", "Rosfa", "Ouled Addouane", "Bellaa", "Ain Arnat", "Amoucha", "Ain Oulmane", "Beidha Bordj", "Bouandas", "Bazer Sakra", "Hammam Skhouna", "Mezloug", "Bir Haddada", "Serdj El Ghoul", "Harbil", "El Ouricia", "Tizi Nbechar", "Salah Bey", "Ain Azal", "Guenzet Tassameurt", "Tala Ifacene", "Bougaa", "Beni Fouda", "Tachouda", "Beni Mouhli", "Ouled Sabor", "Guellal", "Ain Sebt", "Hammam Guergour", "Mzada", "Ksar El Abtal", "Beni Hocine", "Ait Tizi", "Maouklane", "Guelta Zerga", "Oued El Bared", "Taya", "El Oueldja", "Tella"},
            {"(Peu importe)", "Saida", "Doui Thabet", "Ain El Hadjar", "Ouled Khaled", "Moulay Larbi", "Youb", "Hounet", "Sidi Amar", "Sidi Boubekeur", "El Hassasna", "Maamora", "Sidi Ahmed", "Ain Skhouna", "Ouled Brahim", "Tircine", "Ain Soltane"},
            {"(Peu importe)", "Skikda", "Ain Zouit", "El Hadaiek", "Azzaba", "Djendel Saadi Mohamed", "Ain Cherchar", "Bekkouche Lakhdar", "Ben Azzouz", "Es Sebt", "Collo", "Beni Zid", "Kerkera", "Ouled Attia", "Oued Zhour", "Zitouna", "El Harrouch", "Zerdezas", "Ouled Hebaba", "Sidi Mezghiche", "Emdjez Edchich", "Beni Oulbane", "Ain Bouziane", "Ramdane Djamel", "Beni Bachir", "Salah Bouchaour", "Tamalous", "Ain Kechra", "Oum Toub", "Bir El Ouiden", "Fil Fila", "Cheraia", "Kanoua", "El Ghedir", "Bouchtata", "Ouldja Boulbellout", "Kheng Mayoum", "El Marsa", "Hamadi Krouma"},
            {"(Peu importe)", "Sidi Bel Abbes", "Tessala", "Sidi Brahim", "Mostefa Ben Brahim", "Telagh", "Mezaourou", "Boukanefis", "Sidi Ali Boussidi", "Bedrabine El Mokrani", "Marhoum", "Tafissour", "Amarnas", "Tilmouni", "Sidi Lahcene", "Ain Thrid", "Makedra", "Tenira", "Moulay Slissen", "El Hacaiba", "Hassi Zahana", "Tabia", "Merine", "Ras El Ma", "Ain Tindamine", "Ain Kada", "Mcid", "Sidi Khaled", "Ain El Berd", "Sfisef", "Ain Adden", "Oued Taourira", "Dhaya", "Zerouala", "Lamtar", "Sidi Chaib", "Sidi Daho", "Oued Sbaa", "Boudjebaa El Bordj", "Sehala Thaoura", "Sidi Yacoub", "Sidi Hamadouche", "Belarbi", "Oued Sefioun", "Teghalimet", "Ben Badis", "Sidi Ali Benyoub", "Chetouane Belaila", "Bir El Hmam", "Taoudmout", "Redjem Demmouche", "Benachiba Chelia", "Hassi Daho"},
            {"(Peu importe)", "Annaba", "Berrahel", "El Hadjar", "Eulma", "El Bouni", "Oued El Aneb", "Cheurfa", "Seraidi", "Ain Berda", "Chetaibi", "Sidi Amer", "Treat"},
            {"(Peu importe)", "Guelma", "Nechmaya", "Bouati Mahmoud", "Oued Zenati", "Tamlouka", "Oued Fragha", "Ain Sandel", "Ras El Agba", "Dahouara", "Belkheir", "Bendjerrah", "Bouhamdane", "Ain Makhlouf", "Ain Ben Beida", "Khezara", "Beni Mezline", "Bouhachana", "Guelaat Bousbaa", "Hammam Debagh", "El Fedjoudj", "Bordj Sabath", "Hammam Nbail", "Ain Larbi", "Medjez Amar", "Bouchegouf", "Heliopolis", "Houari Boumediene", "Roknia", "Seliaoua Announa", "Medjez Sfa", "Boumahra Ahmed", "Ain Reggada", "Oued Cheham", "Djeballah Khemissi"},
            {"(Peu importe)", "Constantine", "Hamma Bouziane", "Ben Badis", "Zighoud Youcef", "Didouche Mourad", "El Khroub", "Ain Abid", "Beni Hamidene", "Ouled Rahmoun", "Ain Smara", "Mesaoud Boudjeriou", "Ibn Ziad"},
            {"(Peu importe)", "Medea", "Ouzera", "Ouled Maaref", "Ain Boucif", "Aissaouia", "Ouled Deide", "El Omaria", "Derrag", "El Guelbelkebir", "Bouaiche", "Mezrenna", "Ouled Brahim", "Tizi Mahdi", "Sidi Ziane", "Tamesguida", "El Hamdania", "Kef Lakhdar", "Chellalat El Adhaoura", "Bouskene", "Rebaia", "Bouchrahil", "Ouled Hellal", "Tafraout", "Baata", "Boghar", "Sidi Naamane", "Ouled Bouachra", "Sidi Zahar", "Oued Harbil", "Ben Chicao", "Sidi Damed", "Aziz", "Souagui", "Zoubiria", "Ksar El Boukhari", "El Azizia", "Djouab", "Chahbounia", "Maghraoua", "Cheniguel", "Ain Ouksir", "Oum El Djalil", "Ouamri", "Si Mahdjoub", "Tlatet Ed Douair", "Beni Slimane", "Berrouaghia", "Seghouane", "Mfatha", "Mihoub", "Boughzoul", "Tablat", "Deux Bassins", "Draa Essmar", "Sidi Errabia", "Bir Ben Abed", "El Aouinet", "Ouled Antar", "Bouaichoune", "Hannacha", "Sedraia", "Moudjebeur", "Khams Djouamaa", "Saneg"},
            {"(Peu importe)", "Mostaganem", "Sayada", "Fornaka", "Stidia", "Ain Nouissi", "Hassi Maameche", "Ain Tedles", "Sour", "Oued El Kheir", "Sidi Belattar", "Kheir Eddine", "Sidi Ali", "Abdelmalek Ramdane", "Hadjadj", "Nekmaria", "Sidi Lakhdar", "Achaacha", "Khadra", "Bouguirat", "Sirat", "Ain Sidi Cherif", "Mesra", "Mansourah", "Souaflia", "Ouled Boughalem", "Ouled Maalah", "Mezaghrane", "Ain Boudinar", "Tazgait", "Safsaf", "Touahria", "El Hessiane"},
            {"(Peu importe)", "Msila", "Maadid", "Hammam Dhalaa", "Ouled Derradj", "Tarmount", "Mtarfa", "Khoubana", "Mcif", "Chellal", "Ouled Madhi", "Magra", "Berhoum", "Ain Khadra", "Ouled Addi Guebala", "Belaiba", "Sidi Aissa", "Ain El Hadjel", "Sidi Hadjeres", "Ouenougha", "Bousaada", "Ouled Sidi Brahim", "Sidi Ameur", "Tamsa, Ben Srour", "Ouled Slimane", "El Houamed", "El Hamri", "Ouled Mansour", "Maarif", "Dehahna", "Bouti Sayeh", "Khettouti Sed El Djir", "Zerzour", "ohamed Boudiaf", "Benzouh", "Bir Fodda", "Ain Fares", "Sidi Mhamed", "Menaa", "Soumaa", "Ain El Melh", "Medjedel", "Slim", "Ain Errich", "Beni Ilmene", "Oultene", "Djebel Messaad"},
            {"(Peu importe)", "Mascara", "Bouhanifia", "Tizi", "Hacine", "Maoussa", "Tighennif", "El Hachem", "Sidi Kada", "Zelmata", "Oued El Abtal", "Ain Ferah", "Ghriss", "Froha", "Matmore", "Makda", "Sidi Boussaid", "El Bordj", "Ain Fekan", "Benian", "Khalouia", "El Menaouer", "Oued Taghia", "Aouf", "Ain Fares", "Ain Frass", "Sig", "Oggaz", "Alaimia", "El Gaada", "Zahana", "Mohammadia", "Sidi Abdelmoumene", "Ferraguig", "El Ghomri", "Sedjerara", "Moctadouz", "Bouhenni", "El Gueitna", "El Mamounia", "El Keurt", "Gharrous", "Guerdjoum", "Chorfa", "Ras El Ain Amirouche","Nesmoth", "Sidi Abdeldjabar", "Sehailia"},
            {"(Peu importe)", "Ouargla", "Ain Beida", "Ngoussa", "Hassi Messaoud", "Rouissat", "Balidat Ameur", "Tebesbest", "Nezla", "Zaouia El Abidia", "Sidi Slimane", "Sidi Khouiled", "Hassi Ben Abdellah", "Touggourt", "El Hadjira", "Taibet", "Tamacine", "Benaceur", "Mnaguer", "Megarine", "El Allia El Borma"},
            {"(Peu importe)", "Oran", "Gdyel", "Bir El Djir", "Hassi Bounif", "Es Senia", "Arzew", "Bethioua", "Marsat El Hadjadj", "Ain Turk", "El Ancor", "Oued Tlelat", "Tafraoui", "Sidi Chami", "Boufatis", "Mers El Kebir", "Bousfer", "El Karma", "El Braya", "Hassi Ben Okba", "Ben Freha", "Hassi Mefsoukh", "Sidi Ben Yabka", "Misserghin", "Boutlelis", "Ain Kerma", "Ain Biya"},
            {"(Peu importe)", "El Bayadh", "Rogassa", "Stitten", "Brezina", "Ghassoul", "Hadj Mechri Boualem", "El Abiodh Sidi Cheikh", "Ain El Orak", "Arbaouat", "Bougtoub", "El Kheither", "Kef El Ahmar", "Boussemghoun", "Chellala", "Krakda", "El Bnoud", "Cheguig", "Sidi Ameur", "El Mehara", "Tousmouline", "Sidi Slimane", "Sidi Tifour"},
            {"(Peu importe)", "Illizi", "Djanet", "Debdeb", "Bordj Omar Driss", "Bordj El Haoues", "In Amenas"},
            {"(Peu importe)", "Bordj Bou Arreridj", "Ras El Oued", "Bordj Zemoura", "Mansoura", "El Mhir", "Bendaoud", "El Achir", "Ain Taghrout", "Bordj Ghdir", "Sidi Embarek", "El Hammadia", "Belimour", "Medjana", "Theniet El Anseur", "Djaafra", "El Main", "Ouled Brahem", "Ouled Dahmane", "Hasnaoua", "Khelil", "Taglait", "Ksour", "Ouled Sidi Brahim", "Tafreg", "Colla", "Tixter", "El Euch", "El Anseur", "Tesmart", "Ain Tassera", "Bir Kasdali", "Ghilassa", "Rabta", "Haraza"},
            {"(Peu importe)", "Boumerdes", "Boudouaou", "Afir", "Bordj Menaiel", "Baghlia", "Sidi Daoud", "Naciria", "Djinet", "Isser", "Zemmouri", "Si Mustapha", "Tidjelabine", "Chabet El Ameur", "Thenia", "Timezrit", "Corso", "Ouled Moussa", "Larbatache", "Bouzegza Keddara", "Taourga", "Ouled Aissa", "Ben Choud", "Dellys", "Ammal", "Beni Amrane", "Souk El Had", "Boudouaou El Bahri", "Ouled Hadjadj", "Laghata", "Hammedi", "Khemis El Khechna", "El Kharrouba"},
            {"(Peu importe)", "El-tarf", "Bouhadjar", "Ben Mhidi", "Bougous", "El Kala", "Ain El Assel", "El Aioun", "Bouteldja", "Souarekh", "Berrihane", "Lac Des Oiseaux", "Chefia", "Drean", "Chihani", "Chbaita Mokhtar", "Besbes", "Asfour", "Echatt", "Zerizer", "Zitouna", "Ain Kerma", "Oued Zitoun", "Hammam Beni Salah", "Raml Souk"},
            {"(Peu importe)", "Tindouf", "Oum El Assel"},
            {"(Peu importe)", "Tissemsilt", "Bordj Bounaama", "Theniet El Had", "Lazharia", "Beni Chaib", "Lardjem", "Melaab", "Sidi Lantri", "Bordj El Emir Abdelkader", "Layoune", "Khemisti", "Ouled Bessem", "Ammari", "Youssoufia", "Sidi Boutouchent", "Larbaa", "Maacem", "Sidi Abed", "Tamalaht", "Sidi Slimane", "Boucaid", "Beni Lahcene"},
            {"(Peu importe)", "El Oued", "Robbah", "Oued El Alenda", "Bayadha", "Nakhla", "Guemar", "Kouinine", "Reguiba", "Hamraia", "Taghzout", "Djebila", "Hassani Abdelkrim", "Hassi Khelifa", "Taleb Larbi", "Douar El Ma", "Sidi Aoun", "Trifaou", "Magrane", "Beni Guecha", "Ourmes", "Still", "Mrara", "Sidi Khellil", "Tendla", "El Ogla", "Mih Ouensa", "El Mghair", "Djamaa", "Oum Tiour", "Sidi Amrane"},
            {"(Peu importe)", "Khenchela", "Mtoussa", "Kais", "Baghai", "El Hamma", "Ain Touila", "Taouzianat", "Bouhmama", "El Oueldja", "Remila", "Cherchar", "Djellal", "Babar", "Tamza", "Ensigha", "Ouled Rechache", "El Mahmal", "Msara", "Yabous", "Khirane", "Chelia"},
            {"(Peu importe)", "Souk-ahras", "Sedrata", "Hanancha", "Mechroha", "Ouled Driss", "Tiffech", "Zaarouria", "Taoura", "Drea", "Haddada", "Khedara", "Merahna", "Ouled Moumen", "Bir Bou Haouch", "Mdaourouche", "Oum El Adhaim", "Ain Zana", "Ain Soltane", "Quillen", "Sidi Fredj", "Safel El Ouiden", "Raggouba", "Khemissa", "Oued Keberit", "Terraguelt", "Zouabi"},
            {"(Peu importe)", "Tipaza", "Menaceur", "Larhat", "Douaouda", "Bourkika", "Khemisti", "Aghbal", "Hadjout", "Sidi Amar", "Gouraya", "Nador", "Chaiba", "Ain Tagourait", "Cherchel", "Damous", "Meurad", "Fouka", "Bou Ismail", "Ahmer El Ain", "Bouharoun", "Sidi Ghiles, Messelmoun", "Sidi Rached", "Kolea", "Hattatba", "Sidi Semiane", "Beni Milleuk", "Hadjeret Ennous"},
            {"(Peu importe)", "Mila", "Ferdjioua", "Chelghoum Laid", "Oued Athmania", "Ain Mellouk", "Telaghma", "Oued Seguen", "Tadjenanet", "Benyahia Abderrahmane", "Oued Endja", "Ahmed Rachdi", "Ouled Khellouf", "Tiberguent", "Bouhatem", "Rouached", "Tassala Lemtai", "Grarem Gouga", "Sidi Merouane", "Tassadane Haddada", "Derradji Bousselah", "Minar Zarza", "Amira Arres", "Terrai Bainem", "Hamala", "Ain Tine", "El Mchira", "Sidi Khelifa", "Zeghaia", "El Ayadi Barbes", "Ain Beida Harriche", "Yahia Beni Guecha", "Cheraga"},
            {"(Peu importe)", "Ain-defla", "Miliana", "Boumedfaa", "Khemis Miliana", "Hammam Righa", "Arib", "Djelida", "El Amra", "Bourached", "El Attaf", "El Abbadia", "Djendel", "Oued Chorfa", "Ain Lechiakh", "Oued Djemaa", "Rouina", "Zeddine", "El Hassania", "Bir Ouled Khelifa", "Ain Soltane", "Tarik Ibn Ziad", "Bordj Emir Khaled", "Ain Torki", "Sidi Lakhdar", "Ben Allal", "Ain Benian", "El Hoceinia", "Barbouche", "Djemaa Ouled Cheikh", "Mekhatria", "Bathia", "Tachta Zegarra", "Ain Bouyahia", "El Mayene", "Tiberkanine", "Belaas"},
            {"(Peu importe)", "Naama", "Mechria", "Ain Sefra", "Tiout", "Sfissifa", "Moghrar", "Asla", "Djenien Bourezg", "Ain Ben Khelil", "Mekmen Ben Amar", "Kasdir", "El Biod"},
            {"(Peu importe)", "Ain-temouchent", "Chaabet El Ham", "Ain Kihel", "Hammam Bouhadjar", "Bouzedjar", "Oued Berkeche", "Aghlal", "Terga", "Ain El Arbaa", "Tamzougha", "Chentouf", "Sidi Ben Adda", "Ougbellil", "El Malah", "Sidi Boumediene", "Oued Sebbah", "Ouled Boudjemaa", "Ain Tolba", "El Amria", "Hassi El Ghella", "Hassasna", "Ouled Kihal", "Beni Saf", "Sidi Safi", "Oulhaca Gherraba", "Tadmaya", "El Emir Abdelkader", "El Msaid"},
            {"(Peu importe)", "Ghardaia", "Golea", "Dhayet Bendahoua", "Berriane", "Metlili", "El Guerrara", "El Atteuf", "Zelfana", "Sebseb", "Bounoura", "Hassi Lefhal", "Hassi El Garaa", "El Mansoura"},
            {"(Peu importe)", "Relizane", "Oued Rhiou", "Belaassel Bouzegza", "Sidi Saada", "Ouled Yaich", "Sidi Lazreg", "El Hmadna", "Sidi Mhamed Ben Ali", "Mediouna", "Sidi Khettab", "Ammi Moussa", "Zemmoura", "Beni Dergoun", "Djidiouia", "El Guettar", "El Hamri", "El Matmar", "Sidi Mhamed Benaouda", "Ain Tarek", "Oued Essalem", "Ouarizane", "Mazouna", "Kalaa", "Ain Rahma", "Yellel", "Oued El Djemaa", "Ramka", "Mendes", "Lahlef", "Beni Zentis", "Souk El Had", "Dar Ben Abdellah", "El Hassi", "Had Chekkala", "Ben Daoud", "El Oueldja", "Merdjet Sidi Abed", "Ouled Sidi Mihoub"},
    };
    //public static final CharSequence commune[] = new CharSequence[] {"c1", "c2", "c3"};
    public static final String FIREBASE_URL = BuildConfig.UNIQUE_FIREBASE_ROOT_URL;
    public static final String FIREBASE_LOCATION_USERS = "users";
    public static final String FIREBASE_LOCATION_TRIPS = "trips";
    public static final String FIREBASE_LOCATION_MESSAGES = "messages";
    public static final String FIREBASE_LOCATION_NOT = "notifications";
    public static final String FIREBASE_LOCATION_STATS = "statistics";
    public static final String FIREBASE_LOCATION_REQ = "requests";

    /**
     * Constants for Firebase object properties
     */
    public static final String FIREBASE_PROPERTY_LIST_NAME = "listName";
    public static final String FIREBASE_PROPERTY_TIMESTAMP_LAST_CHANGED = "timestampLastChanged";
    public static final String FIREBASE_PROPERTY_TIMESTAMP = "timestamp";
    public static final String FIREBASE_PROPERTY_ITEM_NAME = "itemName";

    /**
     * Constants for Firebase URL
     */


    public static final String FIREBASE_URL_USERS = FIREBASE_URL + "/" + FIREBASE_LOCATION_USERS;
    public static final String FIREBASE_URL_TRIPS = FIREBASE_URL + "/" + FIREBASE_LOCATION_TRIPS;
    public static final String FIREBASE_URL_NOT = FIREBASE_URL + "/" + FIREBASE_LOCATION_NOT;
    public static final String FIREBASE_URL_MESSAGES = FIREBASE_URL + "/" + FIREBASE_LOCATION_MESSAGES;
    public static final String FIREBASE_URL_REQ = FIREBASE_URL + "/" + FIREBASE_LOCATION_STATS + "/" + FIREBASE_LOCATION_REQ;


    public static final String KEY_GOOGLE_EMAIL = "GOOGLE_EMAIL";
    /**
     * Constants for Firebase login
     */
    public static final String PASSWORD_PROVIDER = "password";
    public static final String GOOGLE_PROVIDER = "google";
}
